# Generated by Django 5.2.17 on 2026-09-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=200, verbose_name='Имя')),
                ('author_position', models.CharField(blank=True, max_length=300, verbose_name='Должность')),
                ('author_company', models.CharField(blank=True, max_length=300, verbose_name='Компания / Ресторан')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['order'],
            },
        ),
    ]
