# Generated by Django 5.2.17 on 2026-09-10 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='categories/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='Slug')),
                ('article', models.CharField(blank=True, max_length=50, verbose_name='Артикул')),
                ('description', models.TextField(verbose_name='Описание')),
                ('composition', models.TextField(blank=True, verbose_name='Состав')),
                ('calories', models.PositiveIntegerField(blank=True, null=True, verbose_name='Калорийность (ккал/100г)')),
                ('protein', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Белки (г)')),
                ('fat', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Жиры (г)')),
                ('carbs', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Углеводы (г)')),
                ('shelf_life', models.CharField(blank=True, max_length=200, verbose_name='Срок годности')),
                ('storage_conditions', models.CharField(blank=True, max_length=300, verbose_name='Условия хранения')),
                ('meat_type', models.CharField(blank=True, choices=[('', 'Не указано'), ('beef', 'Говядина'), ('pork', 'Свинина'), ('chicken', 'Курица'), ('turkey', 'Индейка'), ('fish', 'Рыба')], max_length=20, verbose_name='Тип мяса')),
                ('cooking_method', models.CharField(blank=True, choices=[('', 'Не указано'), ('frying', 'Жарка'), ('boiling', 'Варка'), ('baking', 'Запекание'), ('steaming', 'На пару')], max_length=20, verbose_name='Способ приготовления')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемый')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новинка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Вес (кг)')),
                ('price_on_request', models.BooleanField(default=True, verbose_name='Цена по запросу')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packagings', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Фасовка',
                'verbose_name_plural': 'Фасовки',
                'ordering': ['weight_kg'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Изображение')),
                ('alt', models.CharField(blank=True, max_length=300, verbose_name='ALT')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главное фото')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Фото товара',
                'verbose_name_plural': 'Фото товаров',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TTKFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название файла')),
                ('pdf', models.FileField(upload_to='ttk/', verbose_name='PDF-файл')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ttk_files', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'ТТК',
                'verbose_name_plural': 'ТТК',
            },
        ),
    ]
